import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Oregano } from 'next/font/google';

const oregano = Oregano ({
  style: ['normal'],
  subsets: ["latin"],
  variable: "--font-oregano",
  preload: true,
  weight: "400"
})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${oregano.variable}`}>{children}</body>
    </html> 
  )
}
